name: appwritex
description: Provides additional features to the Appwrite Dart SDK non-invasively.
version: 0.1.0
repository: https://github.com/insightoptech/appwritex
homepage: https://github.com/insightoptech/appwritex

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.14.0
  dart_appwrite: ^11.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
