name: appwritex
description: A Appwrite extension package for Dart and Flutter.
version: 1.0.0
repository: https://github.com/insightoptech/apwritex
homepage: https://github.com/insightoptech/apwritex

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.14.0
  dart_appwrite: ^11.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
