name: appwritex
description: Provides additional features to the Appwrite Dart SDK non-invasively.
version: 0.2.2
repository: https://github.com/insightoptech/appwritex
homepage: https://github.com/insightoptech/appwritex

environment:
  sdk: ^3.3.0

dependencies:
  ############ For realtime ############
  flutter:
    sdk: flutter # for package:flutter/foundation.dart of realtime
  universal_html: ^2.2.4 # for realtime
  flutter_web_auth_2: ^3.1.2 # for realtime
  cookie_jar: ^4.0.8
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  http: ">=0.13.6 <2.0.0"
  web_socket_channel: ^2.4.5
  ############ For realtime ############

  meta: ^1.11.0
  equatable: ^2.0.5

  dart_appwrite: ^11.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mockito: ^5.4.0
