name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  workflow_dispatch:
concurrency:
  # Cancels the workflow
  # when another event in the same context happens.
  # If it's a PR, context is the pull request number.
  # Otherwise, it uses the Git reference(branch or tag name).
  group: >
    ${{ github.workflow }}
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: ${{ matrix.runner }} / ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    strategy:
      fail-fast: false # Important
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        target: [android, web] # On all platforms
        include:
          # Specify targets for each platform
          - runner: ubuntu-latest
            target: linux
          - runner: windows-latest
            target: windows
          - runner: macos-latest
            target: macos
          - runner: macos-latest
            target: ios
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      # - name: Setup Ninja and GTK3 toolchain (Only Linux target)
      #   if: matrix.target == 'linux'
      #   run: |
      #     sudo apt-get update -y
      #     sudo apt-get install -y ninja-build libgtk-3-dev

      # - name: Setup Java toolchain (Only Android target)
      #   if: matrix.target == 'android'
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: "zulu"
      #     java-version: "11"
      #     cache: "gradle"

      - name: Fetch Dart dependencies
        run: dart pub get

      - name: Build target(Linux)
        if: matrix.target == 'linux'
        run: dart build linux --verbose

      - name: Build target(Android)
        if: matrix.target == 'android'
        run: |
          dart build apk --verbose
          dart build appbundle --verbose

      - name: Build target(Windows)
        if: matrix.target == 'windows'
        run: dart build windows --verbose

      - name: Build target(MacOS)
        if: matrix.target == 'macos'
        run: dart build macos --verbose

      - name: Build target(iOS)
        if: matrix.target == 'ios'
        working-directory: test_app/
        run: dart build ios --verbose --no-codesign

      - name: Build target(Web)
        if: matrix.target == 'web'
        run: dart build web --verbose
