name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  workflow_dispatch:
concurrency:
  # Cancels the workflow
  # when another event in the same context happens.
  # If it's a PR, context is the pull request number.
  # Otherwise, it uses the Git reference(branch or tag name).
  group: >
    ${{ github.workflow }}
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: ${{ matrix.runner }} #/ ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    strategy:
      fail-fast: false # Important
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Fetch Dart dependencies
        run: dart pub get

      - name: Run tests
        run: dart test -r github  --verbose-trace
